### PR TITLE
Add specific check for unix backtrace

### PR DESCRIPTION
**Pull request by xloem**
Aids building on other platforms than just apple and cygwin, that lack this.

### CODE REVIEW

**Comment by linas** [comment]
This is confusing and incorrect -- one has to have `libbfd` and also `libiberty` and also `execinfo.h` to have backtraces. The check for `execinfo.h` should not be needed, since it comes automatically with `libc-dev` and if you don't have `libc`, far ore is likely to be broken.  Is your libc actually missing `execinfo.h` ??

I don't mind the general intent here -- to create a `UnixBacktrace.cmake`, but that file should then contain all the right stuff i it.

**Comment by linas** [comment]
I'm going to close for now, please re-open when you've reorganized everything...

**Comment by xloem** [comment]
hi, uclibc-dev and non-linux platforms often don't have execinfo.h, creating issues compiling the backtrace code.  this was to aid building in Termux on Android.  I'll do it properly and resubmit if I set up that environment again.

**Comment by linas** [comment]
Yes, please. Thank you for the work, it just looked half-finished, and sometimes merging half-finished code makes things worse, not better.

Are you thinking of porting the atomspace as well?

**Comment by xloem** [comment]
I think we had a miscommunication.  by "unix backtrace" I simply meant the availability of `backtrace(3)` and `backtrace_symbols(3)`, which are used by the current backtrace code even if `libbfd` and `libiberty` are unavailable.  These gnu linux extensions are only present if execinfo.h is present.  Would you accept a cosmetic change to the code to make these clearer, such as renaming `FindUnixBacktrace.cmake` to `FindGNUExecInfo.cmake`?

Yes, I have made some progress on porting atomspace as well.

**Comment by linas** [comment]
Ah, OK, yes, indeed, my fault, I misunderstood; it's been so long that I forgot that the backtrace itself was distinct from the pretty-printing.  Yes, `FindGNUExecInfo` would indeed help lessen the confusion!  Thanks!

**Comment by linas** [comment]
I re-opened the pull req, but now there are conflicts in cmake ...

**Comment by xloem** [comment]
I force-pushed a different changeset.  How's this look?

**Comment by linas** [comment]
Thank you, this looks good.

**Pull request merged**
