### PR TITLE
Remove crufty, unused code.

### PR DESCRIPTION
**Pull request by linas**
Remove code that appears to be unused, un-needed.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Some of that code is used by moses, such as `count_bits`. Let see if we can list them...

**Comment by ngeiswei** [comment]
Functions or classes used
```
next_power_of_two
integer_log2
nbits_to_pack
count_bits
```

Functions or classes not used
```
bits
count_bits32
logsum
```

**Comment by linas** [comment]
goo thing this wasn't hastily merged :-)

**Comment by ngeiswei** [comment]
@linas, I'm closing to avoid merging it by accident, please open again if you wish to push commits on top of it.

**Pull request closed without merging**
