### PR TITLE
compile on clang

### PR DESCRIPTION
**Pull request by maparent**
Compiled with `env CXXFLAGS="-std=c++11" LDFLAGS="-lstdc++" cmake ..`
All tests pass on clang (4 fail using gcc9)
Also checked that tests still pass on a Ubuntu 18.04 machine.

### CODE REVIEW

**Comment by maparent** [comment]
I'm a bit confused: https://circleci.com/gh/opencog/cogutil/275 succeeded but github is still referring to https://circleci.com/gh/opencog/cogutil/274 which failed.

**Comment by ngeiswei** [comment]
I've re-run the tests and there are still the errors on moses and as-moses. Same errors on my system (gcc 8.3).

**Comment by maparent** [comment]
The latest error could well be an artifact. Could someone re-trigger the opencog test?

**Comment by linas** [comment]
I retriggered the test. The opencog failure is almost surely a blip.

**Comment by linas** [comment]
@ngeiswei since you last tested, ther was one more commit. Are you still getting errors? Because otherwise, I think this is mergable.

**Comment by ngeiswei** [comment]
Works locally too, I'm merging. Thank @maparent .

**Pull request merged**
