### PR TITLE
add Find*.cmake files from opencog(issue #113)

### PR DESCRIPTION
**Pull request by noskill**
As part of the work on issue #113 moving some cmake files from opencog

### CODE REVIEW

**Comment by vsbogd** [comment]
looks good for me, but didn't tried to make clean build yet

**Comment by vsbogd** [comment]
@linas , @ngeiswei, I think it is ready to be merged, if you don't have any objections I would merge it.

**Comment by ngeiswei** [comment]
I didn't look at it but I trust your judgment, @vsbogd. Just wait for @linas' approval.

**Comment by linas** [comment]
That is, I have no objections. I'm just feeling wishy-washy about it.

**Comment by noskill** [comment]
@linas It would be better to provide config-file package for link-grammar too

**Comment by vsbogd** [comment]
I have made some analysis and found that 4 of these libraries are actually not used by OpenCog and at least one should be converted to *Config.cmake actually. Below is the list of moved libraries with comments. Anyway I would raise additional PRs for these changes.

Not used:
- FindGSL.cmake - not used by opencog/opencog
- FindIODBC.cmake - not used by opencog/opencog
- FindLibMemCached.cmake - not used by opencog/opencog
- FindSDL_gfx.cmake - required by opencog/opencog (message is "SDL_gfx missing: needed for Spatial tools (MapExplorer, MapTools, etc.)." but looks like it is not used actually, and I cannot find sources for MapExplorer and MapTools only .dox files

Can be converted to *Config.cmake
- FindMOSES.cmake - MOSESConfig.cmake should be generated instead
- FindLinkGrammar.cmake - most proper way is to convert it into LinkGrammarConfig.cmake, but LinkGrammar itself is not cmake project

Used in opencog/opencog only:
- FindGHC.cmake - more or less universal it can be used by opencog/atomspace as it also builds Haskell bindings but it is not used in fact
- FindOctomap.cmake - used in opencog/opencog only
- FindUUID.cmake - used in opencog/opencog only
- Findcpprest.cmake - used in opencog/opencog only

**Comment by vsbogd** [comment]
Thanks @noskill !

**Pull request merged**
